services:
  db:
    image: postgres
    volumes:
      - ./.docker/postgres-data:/var/lib/postgresql/data
    env_file:
      - ./.env
    ports:
      - "${POSTGRES_PORT?5432}:5432"
    networks:
      test-net:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    volumes:
      - .:/usr/src/app
    env_file:
      - ./.env
    environment:
      DATABASE_URL: "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db/${POSTGRES_DB}"
    restart: unless-stopped
    networks:
      test-net:

networks:
  test-net:
